package resmed.hi.demo.rules

global resmed.hi.demo.rules.alerts.RulesOutcome rulesOutcome

import resmed.hi.demo.rules.parameters.RuleParameter
import resmed.hi.demo.rules.facts.SummaryData

rule "metric above threshold"
  when
    $param: RuleParameter(operator == Operator.ABOVE)
    // $threshold: $param(this.threshold())
  then
    System.out.println("Above: >>" + $param.toString());
end

rule "metric below threshold"
  when
    $param: RuleParameter(operator == Operator.BELOW)
  then
    System.out.println("Below: >>" + $param.toString());
end
